apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nginx
  newName: alpine # <==== 신규 image name 
  newTag: 3.8 # <==== 신규 tag information
patches:
- relica_count.yaml
- cpu_count.yaml
resources:
- ../../base
